export CUDA_VISIBLE_DEVICES=0
cd ..
python -u run.py \
    --is_training 1 \
    --device cuda \
    --dataset_name action \
    --train_data_paths /home/huangzhe/PrenRNN/data/kth_action/processed_128 \
    --valid_data_paths /home/huangzhe/PrenRNN/data/kth_action/processed_128 \
    --save_dir checkpoints/kth_sam \
    --gen_frm_dir results/kth_sam \
    --model_name sam \
    --reverse_input 1 \
    --img_width 128 \
    --img_channel 1 \
    --input_length 10 \
    --total_length 20 \
    --num_hidden 128,128,128,128 \
    --filter_size 5 \
    --stride 1 \
    --patch_size 4 \
    --layer_norm 0 \
    --scheduled_sampling 1 \
    --sampling_stop_iter 50000 \
    --sampling_start_value 1.0 \
    --sampling_changing_rate 0.00002 \
    --lr 0.0003 \
    --batch_size 4 \
    --max_iterations 80000 \
    --display_interval 1000 \
    --test_interval 5000 \
    --snapshot_interval 5000