export CUDA_VISIBLE_DEVICES=0
cd ..  # 如果需要返回到项目根目录
python -u run.py \
    --is_training 1 \
    --device cuda \
    --dataset_name tianchi \
    --train_data_paths /home/huangzhe/PrenRNN/data/tianchi-example/train.rar \
    --valid_data_paths /home/huangzhe/PrenRNN/data/tianchi-example/validation.rar \
    --save_dir checkpoints/tianchi_dam \
    --gen_frm_dir results/tianchi_dam \
    --model_name dam \
    --reverse_input 1 \
    --img_width 128 \
    --img_channel 3 \
    --input_length 5 \
    --total_length 15 \
    --num_hidden 128,128,128,128 \
    --filter_size 5 \
    --stride 1 \
    --patch_size 4 \
    --layer_norm 0 \
    --scheduled_sampling 1 \
    --sampling_stop_iter 5000 \
    --sampling_start_value 1.0 \
    --sampling_changing_rate 0.0002 \
    --lr 0.0003 \
    --batch_size 4 \
    --max_iterations 8000 \
    --display_interval 100 \
    --test_interval 500 \
    --snapshot_interval 500
